// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnrkmfjfowefadecwxsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJucmttZmpmb3dlZmFkZWN3eHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjY4OTIsImV4cCI6MjA2MjAwMjg5Mn0.AboRBWZSGLyWUOE8HF4NK4CLQav34eXxE6VAIFRDKrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);